swagger: "2.0"
info:
  description: This is the swagger file that goes with SHS Camera Module
  version: "1.0.0"
  title: Camera module
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"
paths:
  /status/{statusNumber}:
    post:
      operationId: "edgeapi.status"
      summary: "Arms or unarms the status"
      parameters:
        - name: statusNumber
          in: path
          description: Status id. 0 for armed, 1 for unarmed.
          required: True
          type : "integer"
      responses:
        200:
          description: "Successfully set"
	400:
	  description: "Invalid Status Number"